apiVersion: v1
kind: Service
metadata:
  name: prometheus-demo
spec:
  type: LoadBalancer
  ports:
  - port: 9999
    targetPort: 8080
  selector:
    app: prometheus-demo-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-demo-metrics
spec:
  selector:
    matchLabels:
      app: prometheus-demo-metrics
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-demo-metrics
    spec:
      containers:
      - name: prometheus-demo-metrics
        image: bpschmitt/prometheus-metrics-demo:1.0
        resources:
          limits:
            memory: 128M
            cpu: 100m
        ports:
        - containerPort: 8080
      restartPolicy: Always