---
apiVersion: v1
kind: Service
metadata:
  name: logs-demo
spec:
  ports:
    - port: 8000
      targetPort: 4000
  selector:
    app: logs-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-demo
spec:
  selector:
    matchLabels:
      app: logs-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: logs-demo
    spec:
      containers:
      - name: nodejs-logs-k8s
        image: bpschmitt/nodejs-logs-k8s:0.5
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256M"
            cpu: "250m"
        ports:
        - containerPort: 4000
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: nrlicensekey
              key: nrlicensekey
        - name: NEW_RELIC_APP_NAME
          value: "REPLACE_ME"
        - name: APP_TITLE
          value: "REPLACE_ME"
