apiVersion: v1
kind: Pod
metadata:
  name: load-gen
spec:
  containers:
  - name: load-gen
    image: jsha/dnsutils:latest
    # Generate some load to the NGINX service
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do curl -s http://nginx:80; sleep .2; done;" ]